RESUME_HEADERS = {
    'language':[
        'language', 
        'languages', 
        'languages known', 
        ],
    'objective':[
        'ABOUT',
        'Declaration',
        'Description', 
        'objective', 
        'profile', 
        'career goal',
        'personal profile'
        'personal statement'
        'career objective',
        'employment objective',
        'professional objective',        
        'career summary',
        'professional summary',
        'summary of qualifications',
        'summary',
        'synopsis'
        ],
    'projects':[
        'projects',
        'personal projects',

        ],
    'contact_info':[
        'about',
        'contact',
        'contact me at',
        'personal info',
        'contact details',
        'personal information', 
        'personal profile',
        'personal details',
        'get in contact',
        'personal summary'
        ],
    'skills':[
        'skills and rating',
        'skills',
        'key skills',
        'skills summary',
        'credentials',
        'EXPERTISE',
        'areas of experience',
        'areas of knowledge',
        'AREAS OF EXPERTISE',
        'skills',
        "other abilities",
        'career related skills',
        'KEY SKILLS AND COMPETENCIES',
        'skills & proficiencies',
        'professional skills',
        'specialized skills',
        'technical skills',
        'computer skills',
        'computer knowledge',        
        'technologies',
        'technical experience',
        'proficiencies',
        'Technologies Used',
        'language competencies and skills',
        'programming languages',
        'competencies'
        ],
    'work_and_employment':[
        'work experience',
        'career profile',
        'employment history',
        'work history',
        'work experience',
        'experience',
        'professional experience',
        'professional experience',
        'professional background',
        'additional experience',
        'career related experience',
        'related experience',
        'programming experience',
        'freelance',
        'freelance experience',
        'army experience',
        'military experience',
        'military background'
        ],
    'certificate':[
        'certificates', 
        'certifications',
        'misc',
        'miscllaneous',
        'Courses and certifications'
        
        ],
    'education_and_training':[
        'education',
        'education history',
        'academic background',
        'academic experience',
        'programs',
        'related courses',
        'education',
        'qualifications',
        'educational background',
        'educational qualifications',
        'educational training',
        'education and training',
        'academic training',
        'ACADEMIC QUALIFICATIONS'
    ],
    'interests':[
        'hobbies', 
        'interests',
        'other skills',
        'Personal Skill',
        'hobbies and interest',
        'inter personal skills',
        'inter-personal skills',
        'interpersonal skills'
        ],
    'awards':[
        'awards',
        'accomplishment',
        'achievement',
        'licenses',
        'presentations',
        'conference presentations',
        'conventions',
        'dissertations',
        'exhibits',
        'papers',
        'publications',
        'professional publications',
        'research',
        'research grants',
        'current research interests',
        'thesis',
        'theses',
        ]
}

EDU_RESERVED_WORDS = [
            'school',
            'university',
            'institute',
            'college',
            'univers',
            'academy',
            'faculty',
            'institute',
            'faculdades',
            'Schola',
            'schule',
            'lise',
            'lyceum',
            'lycee',
            'polytechnic',
            'kolej',
            'ünivers',
            'okul',
        ]
