RESUME_HEADERS = {
    'language':[
        'language', 
        'languages', 
        'languages known', 
        ],
    'objective':[
        'ABOUT',
        'Declaration',
        'Description', 
        'objective', 
        'profile', 
        'career goal',
        'personal profile'
        'personal statement'
        'career objective',
        'employment objective',
        'professional objective',        
        'career summary',
        'professional summary',
        'summary of qualifications',
        'summary',
        'synopsis'
        ],
    'projects':[
        'projects',
        'personal projects',

        ],
    'contact_info':[
        'about',
        'contact',
        'contact me at',
        'personal info',
        'contact details',
        'personal information', 
        'personal profile',
        'personal details',
        'get in contact',
        'personal summary'
        ],
    'skills':[
        'skills and rating',
        'skills',
        'key skills',
        'skills summary',
        'credentials',
        'EXPERTISE',
        'areas of experience',
        'areas of knowledge',
        'AREAS OF EXPERTISE',
        'skills',
        "other abilities",
        'career related skills',
        'KEY SKILLS AND COMPETENCIES',
        'skills & proficiencies',
        'professional skills',
        'specialized skills',
        'technical skills',
        'computer skills',
        'computer knowledge',        
        'technologies',
        'technical experience',
        'proficiencies',
        'Technologies Used',
        'language competencies and skills',
        'programming languages',
        'competencies'
        ],
    'work_and_employment':[
        'work experience',
        'career profile',
        'employment history',
        'work history',
        'work experience',
        'experience',
        'professional experience',
        'professional experience',
        'professional background',
        'additional experience',
        'career related experience',
        'related experience',
        'programming experience',
        'freelance',
        'freelance experience',
        'army experience',
        'military experience',
        'military background'
        ],
    'certificate':[
        'certificates', 
        'certifications',
        'misc',
        'miscllaneous',
        'Courses and certifications'
        
        ],
    'education_and_training':[
        'education',
        'education history',
        'academic background',
        'academic experience',
        'programs',
        'related courses',
        'education',
        'qualifications',
        'educational background',
        'educational qualifications',
        'educational training',
        'education and training',
        'academic training',
        'ACADEMIC QUALIFICATIONS'
    ],
    'interests':[
        'hobbies', 
        'interests',
        'other skills',
        'Personal Skill',
        'hobbies and interest',
        'inter personal skills',
        'inter-personal skills',
        'interpersonal skills'
        ],
    'awards':[
        'awards',
        'accomplishment',
        'achievement',
        'licenses',
        'presentations',
        'conference presentations',
        'conventions',
        'dissertations',
        'exhibits',
        'papers',
        'publications',
        'professional publications',
        'research',
        'research grants',
        'current research interests',
        'thesis',
        'theses',
        ]
}

EDU_RESERVED_WORDS = [
            'school',
            'university',
            'institute',
            'college',
            'univers',
            'academy',
            'faculty',
            'institute',
            'faculdades',
            'Schola',
            'schule',
            'lise',
            'lyceum',
            'lycee',
            'polytechnic',
            'kolej',
            'ünivers',
            'okul',
        ]

DEG_RESERVED_WORDS = [
    'Bachelor of Architecture B.Arch.',
    'Bachelor of Arts B.A. (Honors)',
    'Bachelor of Arts B.A. ',
    'Bachelor of Business B.B.',
    'Bachelor of Business Administration B.B.A.',
    'Bachelor of Science Business B.S.B.',
    'Bachelor of Canon Law B.C.L.',
    'Bachelor of Computer Science B.C.S.',
    'Bachelor of Science Computer Science B.S.C.S.',
    'Bachelor of Criminal Justice B.C.J.',
    'Bachelor of Science Criminal Justice B.S.C.J.',
    'Bachelor of Divinity B.D.',
    'Bachelor of Education B.Ed.',
    'Bachelor of Science Education B.S.Ed.',
    'Bachelor of Wireless Engineering B.W.E.',
    'Bachelor of Engineering B.E.  B.Eng.',
    'Bachelor of Science Engineering B.S.E.  B.S.EN.',
    'Bachelor of Science Aerospace Engineering B.S.A.E.',
    'Bachelor of Science Agricultural Engineering B.S.A.E.',
    'Bachelor of Science Biological Systems B.S.B.S.',
    'Bachelor of Science Biosystems  Agricultural Engineering B.S.B.A.E.',
    'Bachelor of Science Biological Engineering B.S.B.E.',
    'Bachelor of Biomedical Engineering B.B.m.E.',
    'Bachelor of Science Biomedical Engineering B.S.B.E.  B.S.B.M.E.',
    'Bachelor of Science Chemical Engineering B.S.Ch.E.',
    'Bachelor of Science Chemical  Biomolecular Engineering B.S.Ch.B.E.',
    'Bachelor of Science Chemical  Materials Engineering B.S.C.M.E.',
    'Bachelor of Civil Engineering B.C.E.',
    'Bachelor of Science Civil Engineering B.S.C.E.',
    'Bachelor of Science Civil  Infrastructure Engineering B.S.-C.I.E.',
    'Bachelor of Computer Engineering B.Comp.E.',
    'Bachelor of Science Computer Engineering B.S.C.E.  B.S.Cmp.E.',
    'Bachelor of Science Computer Science  Engineering B.S.C.S.E.',
    'Bachelor of Science Electrical  Computer Engineering B.S.E.C.E.',
    'Bachelor of Electrical Engineering B.E.E.',
    'Bachelor of Science Electrical Engineering B.S.E.E.',
    'Bachelor of Science Engineering Management B.S.E.Mgt.',
    'Bachelor of Science Environmental Engineering B.S.En.E.  B.S.Env.E.',
    'Bachelor of Fiber Engineering B.F.E.',
    'Bachelor of Science Industrial Engineering B.S.I.E.',
    'Bachelor of Science Manufacturing Engineering B.S.Mfg.E.',
    'Bachelor of Science Manufacturing Systems Engineering B.S.M.S.E.',
    'Bachelor of Science Materials Science  Engineering B.S.M.S.E.',
    'Bachelor of Science Materials Engineering B.S.MA.E.',
    'Bachelor of Mechanical Engineering B.M.E.',
    'Bachelor of Science Mechanical Engineering B.S.M.E.',
    'Bachelor of Science Metallurgical Engineering B.S.Mt.E.',
    'Bachelor of Science Mining Engineering B.S.MI.E.',
    'Bachelor of Science Systems B.S.-SYST.',
    'Bachelor of Stware Engineering B.S.W.E.',
    'Bachelor of Science Stware Engineering B.S.S.E.',
    'Bachelor of Systems Engineering B.S.E.',
    'Bachelor of Science Systems Engineering B.S.S.E.',
    'Bachelor of Engineering Technology B.E.T.',
    'Bachelor of Science Engineering Technology B.S.E.T.',
    'Bachelor of Science Civil Engineering Technology B.S.C.E.T.  B.S.Civ.E.T.',
    'Bachelor of Science Computer Engineering Technology B.S.C.E.T.',
    'Bachelor of Science Construction Engineering Technology B.S.Con.E.T.',
    'Bachelor of Science Drafting Design Technology B.S.D.D.T.',
    'Bachelor of Science Electrical  Electronics Technology B.S.E.T.',
    'Bachelor of Science Electrical Engineering Technology B.S.E.E.T.',
    'Bachelor of Science Electro-Mechanical Engineering Technology B.S.E.M.E.T.',
    'Bachelor of Science Mechanical Engineering Technology B.S.M.E.T.',
    'Bachelor of Fine Arts B.F.A.',
    'Bachelor of Forestry B.F.',
    'Bachelor of Science Forest Research B.S.For.Res.',
    'Bachelor of Hebrew Letters B.H.L.',
    'Bachelor of Journalism B.J.',
    'Bachelor of Laws LL.B.',
    'Bachelor of Liberal Studies B.L.S.',
    'Bachelor of Literature B.Lit.',
    'Bachelor of Marine Science B.M.S.',
    'Bachelor of Music B.M.',
    'Bachelor of Nursing B.N.',
    'Bachelor of Science Nursing B.S.N.',
    'Bachelor of Pharmacy B.Pharm.',
    'Bachelor of Philosophy B.Phil.',
    'Bachelor of Religious Education B.R.E.',
    'Bachelor of Science B.S.',
    'Bachelor of Science Chemistry B.S.Ch.',
    'Bachelor of Technology B.T. B.Tech.',
    'B Tech in Computer Science'  
]